2022-07-31 18:25:51,939 (2046/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-07-31 18:26:29,909 (2085/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-08-08 21:07:28,622 (312551/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-08-08 21:21:57,339 (312850/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-08-08 21:21:57,386 (312850/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 607, in connect\n    raise e\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 594, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2022-08-08 21:22:18,058 (312891/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-08-08 21:22:18,104 (312891/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 607, in connect\n    raise e\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 594, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2022-08-19 09:51:45,631 (598385/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-08-19 09:51:45,681 (598385/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 607, in connect\n    raise e\n  File "/usr/lib/python3/dist-packages/pgcli/main.py", line 594, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3/dist-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2022-08-19 11:31:25,187 (600382/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-09-12 21:36:34,217 (756201/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
